[package]
name = "meowtsun/bowl"
description = "Modular status system for Luau games"
authors = ["Meowtsun"]
version = "0.0.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]